version = 0.1
[default.deploy.parameters]
stack_name = "listings-app"
resolve_s3 = true
s3_prefix = "listings-app"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
