AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Documentation to connect and interact with Property Listings API.
  
Globals:
  Function:
    Timeout: 10

Resources:
  DDBHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dynamo-handler/
      Handler: app.handler
      Runtime: nodejs18.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ListingsTable
      Events:
        GetListing:
          Type: HttpApi
          Properties:
            Path: /listings/{id}
            Method: GET
        UpdateListing:
          Type: HttpApi
          Properties:
            Path: /listings/{id}
            Method: PUT
        DeleteListing:
          Type: HttpApi
          Properties:
            Path: /listings/{id}
            Method: DELETE
        GetAllListings:
          Type: HttpApi
          Properties:
            Path: /listings
            Method: GET
        CreateListing:
          Type: HttpApi
          Properties:
            Path: /listings
            Method: POST

  ListingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: app-listings
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  ApiEndpoint:
    Description: "The invoke URL for our HTTP API"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/listings"
  Function:
    Description: "DynamoDB handler function ARN"
    Value: !GetAtt DDBHandlerFunction.Arn
